name: Deploy to cts-server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone cts repository
        run: git clone https://github.com/Ajayos/cts publish
        
      - name: Clone Ajayos.github.io repository
        run: git clone --branch gh-pages https://github.com/Ajayos/Ajayos.github.io publish/Pages

      - name: Remove .git from Public
        run: rm -rf publish/Pages/.git
        
      - name: Remove .git from Root
        run: rm -rf publish/.git
        
      - name: Push to cts-server
        run: |
          cd publish
          git init
          git config --global user.email "ajayosakhub@gmail.com"
          git config --global user.name "Ajay o s"
          git remote add cts-server https://github.com/Ajayos/cts-server.git
          git add .
          git commit -m "ğŸ‘¨â€ğŸ’»CODE BY ğŸ•Šï¸â˜…âƒAJAY O SÂ©ï¸ğŸ§šâ€â™‚ï¸"
          git push cts-server master
